const fs = require('fs');

const max = 200;
const data = [];
for (let index = 1; index <= max; index += 1) {
  const userRole = {
    model: 'roles',
    data: {
      id: index,
      userId: index,
      role: 'user',
    },
  };
  data.push(userRole);
}

fs.writeFileSync('autoGeneratedRoles.json', JSON.stringify(data));
