version: '3.7'
# volumes:
#   data:
#     external:
#       name: rest-bff-database-store
services:
  postgres:
    image: postgres
    restart: unless-stopped
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: rest-bff
    # volumes:
    #   - data:/var/lib/postgresql/data
  nginx:
    restart: always
    build:
      context: ./nginx
    container_name: nginx
    ports:
        - 80:80
  users-api:
    container_name: users-api
    build:
      context: ./users-api
    depends_on:
      - postgres
  auth-api:
    container_name: auth-api
    build:
      context: ./auth-api
    depends_on:
      - postgres
  education-api:
    container_name: education-api
    build:
      context: ./education-api
    depends_on:
      - postgres
  skills-api:
    container_name: skills-api
    build:
      context: ./skills-api
    depends_on:
      - postgres
  bff-api:
    container_name: bff-api
    build:
      context: ./bff-api
    depends_on:
      - users-api
      - auth-api
      - skills-api
      - education-api
