openapi: 3.0.1
info:
  title: Users Service REST API
  version: v1
servers:
  - description: 'Local'
    url: 'http://localhost'
tags:
  - description: Users
    name: users
paths:
  /bff/users/all:
    get:
      description: This request retrieves all users
      operationId: getAllUsers
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
          description: OK
        '401':
          description: Unauthorized
        '403':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorInfo'
          description: Forbidden
      tags:
        - users
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        firstname:
          type: string
          example: John
        lastname:
          type: string
          example: Doe
        email:
          type: string
          format: email
          example: john.doe@mail.org
        roles:
          type: array
          items:
            type: string
        skills:
          type: array
          items:
            type: object
            properties:
              tech:
                type: string
              seniority:
                type: string
        education:
          type: array
          items:
            type: object
            properties:
              title:
                type: string
              level:
                type: string
        createdAt:
          type: string
          format: date
          example: 2017-12-06
        updatedAt:
          type: string
          format: date
          example: 2017-12-06
    ErrorInfo:
      type: object
      properties:
        exception:
          type: string
        message:
          type: string
